name: Test Template

on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ inputs.arch }}-test

      - uses: arceos-org/setup-musl@v1
        with:
          arch: ${{ inputs.arch }}

      - name: Build
        run: make ARCH=${{ inputs.arch }} build MODE=debug

      - uses: actions/upload-artifact@v4
        with:
          name: starry-${{ inputs.arch }}
          path: |
            *.bin
            *.elf

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ inputs.arch }}-test

      - name: Setup QEMU
        uses: arceos-org/setup-qemu@v1
        with:
          version: 10.1.0
          arch_list: ${{ inputs.arch }}

      - name: Show environment info
        run: |
          uname -a
          qemu-system-${{ inputs.arch }} --version

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: starry-${{ inputs.arch }}

      - name: Prepare rootfs
        run: |
          make ARCH=${{ inputs.arch }} img

      - name: Test
        run: scripts/ci-test.py ${{ inputs.arch }}
